### ISSUE TITLE
Add new Logo and color scheme for sbt-microsites

### ISSUE THREAD

**Issue by raulraja** [47deg/LambdaTest#10]
John's library needs design for a logo etc. so he can publish a microsite for it.

He doesn't have a specific idea in mind for the logo - so feel free to be creative.

https://47deg.github.io/LambdaTest/

**Comment by Antoniojimenez47** [comment]
Hi! @jorgegalindocruces @israelperezglez 

I have uploaded the brand proposal to Invision:
https://projects.invisionapp.com/d/main#/console/10178183/216781523/preview

Can you review it?

Thank you

**Comment by Antoniojimenez47** [comment]
Hi! @israelperezglez  in Invision I have uploaded the new modifications on the LambdaTest brand.

https://projects.invisionapp.com/d/main#/console/10178183/216781523/preview

Can you review it? Please.

Thanks!

**Comment by Antoniojimenez47** [comment]
Hi! @israelperezglez 
I've uploaded the changes on the LambdaTest brand.
Can you check it? Please

https://projects.invisionapp.com/d/main#/console/10178183/216781523/preview

Thanks!

**Comment by israelperezglez** [comment]
Good Job. LGTM  ;)

**Comment by Antoniojimenez47** [comment]
Hi! @nestorpersist 

I've invited you to Invision to the Lambda Test brand design project.

Check the design and wait for your response to prepare the assets of the microsite.
https://projects.invisionapp.com/d/main#/projects/prototypes/10178183

Thanks!

**Comment by nestorpersist** [comment]
Looks good. Go for it.
