### ISSUE TITLE
Consider using Case classy to avoid config boilerplate

### ISSUE THREAD

**Issue by raulraja** [47deg/LambdaTest#3]
https://github.com/47deg/LambdaTest/blob/master/src/main/scala/com/fortysevendeg/lambdatest/LambdaOptions.scala

This kind of config boilerplate can be easily avoided with https://github.com/47deg/case-classy and will also help us promote this lib as well. Please coordinate with @andyscott to see if there is a good use case for it here.

**Comment by nestorpersist** [comment]
We not add. Options are quite simple. To keep it simple, don't want to add more external dependencies (not just classy but also the stuff it uses).
